name: fieldengineerpro
region: nyc

# Database
databases:
  - name: db
    engine: PG
    version: "16"
    production: true
    
# Services
services:
  # Main Laravel Web Application  
  - name: web
    github:
      repo: nmtechnology/FieldOps-Pro
      branch: main
      deploy_on_push: true
    
    source_dir: /
    
    # Force Docker deployment
    type: DOCKERFILE
    dockerfile_path: Dockerfile
    
    # Environment
    envs:
      - key: APP_NAME
        value: "FieldEngineer Pro"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://fieldengineerpro.com"
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_CONNECTION
        scope: RUN_TIME
        value: "pgsql"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${db.DATABASE_URL}"
      - key: DB_HOST
        scope: RUN_TIME
        value: "${db.HOSTNAME}"
      - key: DB_PORT
        scope: RUN_TIME
        value: "${db.PORT}"
      - key: DB_DATABASE
        scope: RUN_TIME
        value: "${db.DATABASE}"
      - key: DB_USERNAME
        scope: RUN_TIME
        value: "${db.USERNAME}"
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "${db.PASSWORD}"
      # Debug: Add these to see if they're being set
      - key: DEBUG_DB_HOST
        scope: RUN_TIME
        value: "${db.HOSTNAME}"
      - key: DEBUG_DB_URL
        scope: RUN_TIME
        value: "${db.DATABASE_URL}"
      - key: SESSION_DRIVER
        value: "database"
      - key: QUEUE_CONNECTION
        value: "database"
      - key: CACHE_DRIVER
        value: "database"
      - key: LOG_CHANNEL
        value: "stack"
      - key: STRIPE_KEY
        type: SECRET
      - key: STRIPE_SECRET
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        type: SECRET
      - key: COINBASE_COMMERCE_API_KEY
        type: SECRET
      - key: COINBASE_COMMERCE_WEBHOOK_SECRET
        type: SECRET
    
    # HTTP configuration
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Resources
    instance_count: 1
    instance_size_slug: basic-xs
    
  # Queue Worker
  - name: worker
    github:
      repo: nmtechnology/FieldOps-Pro
      branch: main
      deploy_on_push: true
    
    build_command: |
      composer install --no-dev --optimize-autoloader
    
    run_command: php artisan queue:work --tries=3 --timeout=90
    
    envs:
      - key: APP_ENV
        value: "production"
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_CONNECTION
        scope: RUN_TIME
        value: "pgsql"
      - key: DB_HOST
        scope: RUN_TIME
        value: "${db.HOSTNAME}"
      - key: DB_PORT
        scope: RUN_TIME
        value: "${db.PORT}"
      - key: DB_DATABASE
        scope: RUN_TIME
        value: "${db.DATABASE}"
      - key: DB_USERNAME
        scope: RUN_TIME
        value: "${db.USERNAME}"
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "${db.PASSWORD}"
      - key: QUEUE_CONNECTION
        value: "database"
    
    instance_count: 1
    instance_size_slug: basic-xxs

# Domain
domains:
  - domain: fieldengineerpro.com
    type: PRIMARY
  - domain: www.fieldengineerpro.com
    type: ALIAS
